# Generated by Django 5.2.1 on 2025-06-01 05:32

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('market_cap', models.CharField(max_length=200)),
                ('equity_size', models.FloatField()),
                ('high_return', models.FloatField()),
                ('low_return', models.FloatField()),
                ('std_deviation', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('sortino_ratio', models.FloatField()),
                ('beta', models.FloatField()),
                ('alpha', models.FloatField()),
                ('r_squared', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFund',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('market_cap', models.CharField(max_length=200)),
                ('equity_size', models.FloatField()),
                ('high_return', models.FloatField()),
                ('low_return', models.FloatField()),
                ('std_deviation', models.FloatField()),
                ('sharpe_ratio', models.FloatField()),
                ('sortino_ratio', models.FloatField()),
                ('beta', models.FloatField()),
                ('alpha', models.FloatField()),
                ('r_squared', models.FloatField()),
                ('expense_ratio', models.FloatField()),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical fund',
                'verbose_name_plural': 'historical funds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
