# Generated by Django 5.2.1 on 2025-06-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='aum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='lock_in_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='aum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='lock_in_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='nav',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
