# Generated by Django 5.2.1 on 2025-06-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_fund_aum_fund_lock_in_period_fund_nav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='aum',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund',
            name='nav',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='aum',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalfund',
            name='nav',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
