# Generated by Django 5.2.1 on 2025-06-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_fund_aum_alter_fund_nav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='amc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='primary_badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='amc_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='primary_badge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
