# Generated by Django 5.2.1 on 2025-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_fund_amc_name_fund_primary_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='cagr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfund',
            name='cagr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
